remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links

relative_links:
  enabled: true
  collections: true
title: COE Coding Basics Bootcamp
description: A bootcamp for learning the basics of coding
baseurl: "/coe-coding-basics-bootcamp"
url: "https://hackersclubsv.github.io/"

include:
  - index.md
  - pages
